---
- name: Fedora Gnome Playbook
  hosts: all
  pre_tasks:
    - name: System details
      ansible.builtin.debug:
        msg: "{{ item }}"
      with_items: 
      - "{{ ansible_distribution }}"
      - "{{ ansible_distribution_release }}"
      - "{{ ansible_distribution_version }}"
      - "{{ ansible_distribution_major_version }}"
    - name: Update repositories
      become: true
      ansible.builtin.dnf:
        update_cache: true
      changed_when: false
  tasks:
    - include_tasks: tasks/dnf.yml
    - include_tasks: tasks/git.yml
    - include_tasks: tasks/rpmfusion.yml
    - include_tasks: tasks/fedora-packages.yml
    - include_tasks: tasks/main-packages.yml
    - include_tasks: tasks/homebrew.yml
    - name: Install GNOME
      ansible.builtin.include_role:
        name: lorenzobettini.my_gnome_role
      vars:
        modify_dconf: false
    - name: Install Oh My Zsh
      ansible.builtin.include_role:
        name: lorenzobettini.oh_my_zsh
      vars:
        with_starship: false
        copy_dot_files: false
    - name: Install Nerd Fonts
      ansible.builtin.include_role:
        name: lorenzobettini.my_nerd_fonts_role
    # in Fedora 36 we have the new Gnome text editor that looks good!
    - include_tasks: tasks/kde-gnome-packages.yml
      when: ansible_distribution_version is version('36', '<')
    - tags: java
      block:
      - include_tasks: tasks/java-packages.yml
    - include_tasks: tasks/google-chrome.yml
    - include_tasks: tasks/dropbox.yml
    # docker-ce has a few problems (https://ask.fedoraproject.org/t/docker-very-slow-in-fedora/23214)
    - include_tasks: tasks/docker-moby.yml
    - include_tasks: tasks/cronie.yml # required for cron scheduling
    - include_tasks: tasks/recoll.yml
    - include_tasks: tasks/vscode.yml
    - include_tasks: tasks/libreoffice.yml
    - include_tasks: tasks/other-packages.yml
    # not available anymore as a package
    # - include_tasks: tasks/skype.yml
    - include_tasks: tasks/unison.yml
    - tags: latex
      block:
      - include_tasks: tasks/latex.yml

  # post_tasks:
  #   - name: Dist-upgrade
  #     become: true
  #     apt:
  #       upgrade: dist
  #     register: aptout

  #   - debug: msg="{{ aptout.stdout_lines }}"
  #     when: aptout.stdout_lines is defined

  #   - name: Remove useless packages from the cache
  #     become: true
  #     apt:
  #       autoclean: yes

  #   - name: Remove dependencies that are no longer required
  #     become: true
  #     apt:
  #       autoremove: yes
  #     register: aptout

  #   - debug: msg="{{ aptout.stdout_lines }}"
  #     when: aptout.stdout_lines is defined
