- name: Install Amarok
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - amarok
  register: packageout

- debug: msg="{{ packageout.msg }}"
  when: packageout.msg is defined
