- name: Install cronie
  become: true
  ansible.builtin.package:
    state: present
    name:
    - cronie

# No such service in Fedora?
#- name: Enable service cronie
#  become: true
#  ansible.builtin.systemd:
#    name: cronie
#    enabled: yes
