- name: Install cronie
  become: yes
  package:
    state: present
    name:
    - cronie

# No such service in Fedora?
#- name: Enable service cronie
#  become: yes
#  ansible.builtin.systemd:
#    name: cronie
#    enabled: yes
