- name: Ensure docker-ce packages are not installed
  become: yes
  ansible.builtin.dnf:
    state: absent
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Moby
  become: yes
  ansible.builtin.dnf:
    state: absent
    name:
    - moby-engine
    - docker-compose

- name: Allow running Docker without sudo
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

# Then, you have to explicitly start docker.service
# systemctl start docker.service.
# With service module, when running in Docker in molecule
# we get this error FAILED! =>
# "msg": "Could not find the requested service docker: host"
# with systemd module instead it works
- name: Do NOT enable service docker on boot
  become: yes
  ansible.builtin.systemd:
    name: docker.service
    enabled: no

# This way, as soon as we run a docker command docker.service starts
- name: Enable docker.socket on boot
  become: yes
  ansible.builtin.systemd:
    name: docker.socket
    enabled: yes
