- name: Check for Dropbox repo
  ansible.builtin.stat: path=/etc/yum.repos.d/dropbox.repo
  register: fedora_dropbox_installed

- name: Import Dropbox GPG key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: https://linux.dropbox.com/fedora/rpm-public-key.asc
  when: not fedora_dropbox_installed.stat.exists

- name: Install Dropbox
  become: true
  ansible.builtin.dnf:
    name: 'https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2020.03.04-1.fedora.x86_64.rpm'
    state: present
  when: not fedora_dropbox_installed.stat.exists
