- name: Add Dropbox Yum signing key
  become: true
  ansible.builtin.rpm_key:
    key: https://linux.dropbox.com/fedora/rpm-public-key.asc
    state: present
  register: result
  retries: 5
  delay: 10
  until: result is not failed
# downloading from https://linux.dropbox.com/
# is extremely flaky, but ignoring errors might undermine idempotency

- name: Add Dropbox repository into repo.d list
  become: true
  ansible.builtin.yum_repository:
    file: dropbox
    name: Dropbox
    description: Dropbox Repository
    baseurl: http://linux.dropbox.com/fedora/$releasever/
    gpgkey: https://linux.dropbox.com/fedora/rpm-public-key.asc

- name: Install Dropbox
  become: true
  ansible.builtin.dnf:
    name: "nautilus-dropbox"
    state: present
    update_cache: true
  register: result
  retries: 5
  delay: 10
  until: result is not failed
# downloading from https://linux.dropbox.com/
# is extremely flaky, but ignoring errors might undermine idempotency
