- name: Add Dropbox Yum signing key
  become: yes
  rpm_key:
    key: https://linux.dropbox.com/fedora/rpm-public-key.asc
    state: present

- name: Add Dropbox repository into repo.d list
  become: yes
  yum_repository:
    file: dropbox
    name: Dropbox
    description: Dropbox Repository
    baseurl: http://linux.dropbox.com/fedora/$releasever/
    gpgkey: https://linux.dropbox.com/fedora/rpm-public-key.asc

- name: Install Dropbox
  become: yes
  dnf:
    name: "nautilus-dropbox"
    state: present
    update_cache: true
