- name: Install Gnome Packages
  become: yes
  ansible.builtin.package:
    state: present
    name:
    - gnome-tweaks
    - dconf-editor
    - python-psutil
    - gnome-extensions-app
    - guake
    - deja-dup
    - file-roller-nautilus # includes file-roller
    - gnome-screenshot # the original screenshot application
    - eog # Eyes of Gnome

- name: Install Gnome 42 Packages
  become: yes
  ansible.builtin.package:
    state: present
    name:
    - gnome-text-editor
  when: ansible_distribution_version is version('36', '>=')
