- name: Install Chrome
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - google-chrome
  register: packageout

- debug: msg="{{ packageout }}"
  when: packageout is defined
