- name: Add Google Yum signing key
  become: true
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Add Google repository into repo.d list
  become: true
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome repository
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: true

- name: Install google-chrome-stable
  become: true
  ansible.builtin.yum:
    name: "google-chrome-stable"
    state: present
    update_cache: true

# During installation the repo is changed, so we add it again to have idempotency
- name: Add Google repository into repo.d list Again
  become: true
  ansible.builtin.yum_repository:
    name: google-chrome
    description: google-chrome repository
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    skip_if_unavailable: true
    gpgcheck: true
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: true
