- name: Install Guake Drop-down Terminal
  become: yes
  pacman:
    state: present
    name:
    - guake
  register: packageout

- debug: msg="{{ packageout.msg }}"
  when: packageout.msg is defined
