- name: Install Java Packages
  become: yes
  ansible.builtin.dnf:
    state: present
    name:
    - java-17-openjdk-devel
    - java-17-openjdk-src
    - java-11-openjdk-devel
    - java-11-openjdk-src
    - java-1.8.0-openjdk-devel
    - java-1.8.0-openjdk-src

- name: Create Java links directory
  ansible.builtin.file:
    path: '~/.jdk'
    state: directory
    mode: 0775

- name: Create Java links
  ansible.builtin.file:
    src: '/usr/lib/jvm/java-{{ item }}-openjdk'
    dest: '~/.jdk/jdk{{ item }}'
    state: link
  loop:
    - 11
    - 17

- name: Create Java 8 link
  ansible.builtin.file:
    src: '/usr/lib/jvm/java-1.8.0-openjdk'
    dest: '~/.jdk/jdk8'
    state: link

- name: Remove old Java links
  ansible.builtin.file:
    path: '~/.jdk/jdk{{ item }}'
    state: absent
  loop:
    - 1.8.0
    - 16

# This should not be required
# - name: Install libwebkit2gtk (for Eclipse SWT Browser)
#   become: yes
#   pacman:
#     state: present
#     name: libwebkit2gtk-4.0-37
#   register: packageout

# - debug: msg="{{ packageout.msg }}"
#   when: packageout.msg is defined

- name: Install Maven
  ansible.builtin.include_role:
    name: gantsign.maven
  vars:
    maven_version: '3.8.5'
