- name: Install Kde Packages
  become: yes
  pacman:
    state: present
    name:
    - latte-dock
    - yakuake
    - korganizer
    - kaddressbook
    - kwalletmanager
    - ksshaskpass
    - kdepim-addons
    - kio-gdrive
    - dolphin-plugins
    - plasma-systemmonitor
    - kdeplasma-addons
    - kcalc
  register: packageout

- debug: msg="{{ packageout.msg }}"
  when: packageout.msg is defined
