- name: Install Main Packages
  become: yes
  ansible.builtin.package:
    state: present
    name:
    - vim
    - curl
    - wget
    - curl
    - gkrellm
    - net-tools
    - thunderbird
    - util-linux-user # for chsh
    - firewall-applet

# base-devel does not exist
# unison must be taken from COPR
