- name: Install Main Packages
  become: yes
  pacman:
    state: present
    name:
    - base-devel
    - vim
    - curl
    - wget
    - curl
    - gkrellm
    - net-tools
    - unison
    - thunderbird
  register: packageout

- debug: msg="{{ packageout }}"
  when: packageout.msg is defined
