- name: Install Main Packages
  become: yes
  package:
    state: present
    name:
    - vim
    - curl
    - wget
    - curl
    - gkrellm
    - net-tools
    - thunderbird

# base-devel does not exist
# unison must be taken from COPR
