- name: Install Other Packages
  become: yes
  ansible.builtin.package:
    state: present
    name:
    - emacs
    - homebank
    - vlc
    - meld
    - iotop
    - nethogs
    - hyphen-it
    - hunspell-it
    - exfatprogs
#    - ispell
    - aspell
    - gimp
    - tree
    - plocate
    - duf

- name: Enable plocate-updatedb.timer
  become: yes
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes
