- name: Install Other Packages
  become: yes
  package:
    state: present
    name:
    - emacs
    - homebank
    - vlc
    - meld
    - iotop
    - nethogs
    - unrar # from rpmfusion-nonfree
    - hyphen-it
    - hunspell-it
    - exfatprogs
#    - ispell
    - aspell
    - gimp
    - tree
#    - plocate # let's try to stick with mlocate
    - eog # Eyes of Gnome
