- name: Install Other Packages
  become: true
  ansible.builtin.package:
    state: present
    name:
    - emacs
    - homebank
    - vlc
    - meld
    - iotop
    - nethogs
    - hyphen-it
    - hunspell-it
    - exfatprogs
#    - ispell
    - aspell
#    - gimp installed in rpmfusion.yml see comment there
    - tree
    - plocate
    - duf
    - libappindicator-gtk3 # for Variety in Wayland
    - variety
    - powertop
    - neovim
    - nodejs-npm # required for some neovim LSPs, e.g., 
    - shellcheck # required for neovim LSP bashls


- name: Enable plocate-updatedb.timer
  become: true
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes
