- name: Install Other Packages
  become: true
  ansible.builtin.package:
    state: present
    name:
    - emacs
    - homebank
    - vlc
    - meld
    - iotop
    - nethogs
    - hyphen-it
    - hunspell-it
    - exfatprogs
#    - ispell
    - aspell
#    - gimp installed in rpmfusion.yml see comment there
    - tree
    - plocate
    - duf
    - libappindicator-gtk3 # for Variety in Wayland
    - variety
    - powertop
    - neovim
    - nodejs-npm # required for some neovim LSPs, e.g., 
    - shellcheck # required for neovim LSP bashls


- name: Enable plocate-updatedb.timer
  become: true
  ansible.builtin.systemd:
    name: plocate-updatedb.timer
    enabled: yes

- name: Install chezmoi_modify_manager x86_64
  become: true
  ansible.builtin.unarchive:
    src: "https://github.com/VorpalBlade/chezmoi_modify_manager/releases/download/v3.2.0/chezmoi_modify_manager-v3.2.0-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/local/bin
    remote_src: true
