- name: Install Pamac
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - pamac-all
  register: packageout

- debug: msg="{{ packageout.msg }}"
  when: packageout.msg is defined
