- name: Install RPM Fusion
  ansible.builtin.import_role:
    name: robertdebock.rpmfusion
  become: true

- name: install free-release-tainted
  become: true
  ansible.builtin.package:
    name: rpmfusion-free-release-tainted
    state: present

- name: install nonfree-release-tainted
  become: true
  ansible.builtin.package:
    name: rpmfusion-nonfree-release-tainted
    state: present

# Install Gimp now because from RPM fusion we might
# install plugins that require downgrade
- name: Install Gimp
  become: true
  ansible.builtin.package:
    state: present
    name:
    - gimp

- name: Install Fedora Packages from RPM Fusion
  become: true
  ansible.builtin.package:
    state: present
    name:
    - vlc
    - unrar # rpmfusion-nonfree
    - lame
    - "@multimedia"
    - libdvdcss
