- name: Install RPM Fusion
  import_role:
    name: robertdebock.rpmfusion
  become: yes

- name: Install Fedora Packages From RPM Fusion
  become: yes
  package:
    state: present
    name:
    - vlc

