- name: Add Skype Yum signing key
  become: true
  ansible.builtin.rpm_key:
    key: https://repo.skype.com/data/SKYPE-GPG-KEY
    state: present

- name: Add Skype repository into repo.d list
  become: true
  ansible.builtin.yum_repository:
    name: skype-stable
    description: skype (stable)
    baseurl: https://repo.skype.com/rpm/stable/
    gpgcheck: true
    gpgkey: https://repo.skype.com/data/SKYPE-GPG-KEY
    enabled: true

- name: Install Skype
  become: true
  ansible.builtin.dnf:
    name: skypeforlinux
    state: present

# During installation the repo is changed, so we add it again to have idempotency
- name: Add Skype repository into repo.d list Again
  become: true
  ansible.builtin.yum_repository:
    name: skype-stable
    description: skype (stable)
    baseurl: https://repo.skype.com/rpm/stable/
    gpgcheck: true
    gpgkey: https://repo.skype.com/data/SKYPE-GPG-KEY
    enabled: true
