- name: Install Skype
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    state: present
    name:
    - skypeforlinux-stable-bin 
  register: packageout

- debug: msg="{{ packageout.msg }}"
  when: packageout.msg is defined
