- name: Enable project Unison of the user croadfeldt
  become: true
  community.general.copr:
    host: copr.fedorainfracloud.org
    state: enabled
    name: croadfeldt/Unison

- name: Install Unison
  become: true
  ansible.builtin.dnf:
    state: present
    name:
    - unison251-gtk
    - unison251-text