- name: Install Antigen requirements
  become: yes
  ansible.builtin.package:
    state: present
    pkg:
    - powerline-fonts
    - curl
    - git

- name: Download Antigen
  ansible.builtin.get_url:
    url: "https://git.io/antigen"
    dest: "~/antigen.zsh"

- name: Set Antigen configuration
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/tasks/files/antigen/"
    dest: "~/"
