---
# On PR we also test with older versions of the
# Docker images
name: Molecule PR
on:
  pull_request:
    paths-ignore:
     - '**.md'

jobs:

  test:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        playbookdistro:
          - fedora-gnome
        dockerdistro:
          - fedora-35

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: |
          pip install -r pip/requirements.txt

      - name: Show versions.
        run: |
          molecule --version
          yamllint --version
          ansible-lint --version

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.playbookdistro }}
          MOLECULE_DOCKER_DISTRO: ${{ matrix.dockerdistro }}
